---
# tasks file for mgmt-wkst package installation

- name: Update apt repositories cache
  become: true
  apt:
    update_cache: yes

- name: Install openssh-server apt packages
  become: true
  apt:
    name: openssh-server
    state: present

- name: Install ansible module support apt packages
  become: true
  apt:
    name: [ libxml2-dev, libxslt-dev, python-dev, python-lxml, libvirt-dev, python-libvirt, python-netaddr ]
    state: present

- name: Add ansible repository
  become: true
  apt_repository:
    repo: ppa:ansible/ansible

- name: Install ansible apt package
  become: true
  apt:
    name: ansible
    state: present

- name: Install server management apt packages
  become: true
  apt:
    name: ipmitool
    state: present

- name: Install source management apt packages
  become: true
  apt:
    name: git
    state: present

- name: Install bind management tools apt packages
  become: true
  apt:
    name: [ haveged, bind9utils ]
    state: present

- name: Install vagrant apt package
  become: true
  apt:
    deb: "https://releases.hashicorp.com/vagrant/{{vagrant_version}}/vagrant_{{vagrant_version}}_x86_64.deb"
    state: present

- name: Install vagrant plugin support apt packages
  become: true
  apt:
    name: [ gcc, make, libvirt-dev ]
    state: present

- name: Install vagrant base-box building support apt packages
  become: true
  apt:
    name: [ qemu, jq, xmlstarlet]
    state: present
